{
    "drinks": [
        {
            "idDrink": "15288",
            "strDrink": "252",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Shot",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Shot glass",
            "strInstructions": "Add both ingredients to shot glass, shoot, and get drunk quick",
            "strInstructionsES": null,
            "strInstructionsDE": "Beide Zutaten in ein Schnapsglas geben.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg",
            "strIngredient1": "151 proof rum",
            "strIngredient2": "Wild Turkey",
            "strIngredient3": null,
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1/2 shot Bacardi ",
            "strMeasure2": "1/2 shot ",
            "strMeasure3": null,
            "strMeasure4": null,
            "strMeasure5": null,
            "strMeasure6": null,
            "strMeasure7": null,
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": null,
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": "2016-07-18 22:32:42"
        }
    ]
}